### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by stevepeak**
Looks like the coverage package was missing or wrong version. Lets see if this works. Thanks!

### CODE REVIEW

**Comment by stevepeak** [comment]
Looks like Travis is not enabled for pull requests. I'm not confident this fixes the issue...

**Comment by rabernat** [comment]
> Looks like Travis is not enabled for pull requests. I'm not confident this fixes the issue...

They are for pull requests to the org repository. This is my feature branch.

Anyway, thanks for the suggestion. I will merge and try it.

**Comment by stevepeak** [comment]
Here is another suggestion. I think your `.coveragerc` may be off

```
[run]
branch = True

[report]
exclude_lines =
    if self.debug:
    pragma: no cover
    raise NotImplementedError
    if __name__ == .__main__.:
ignore_errors = True
omit = xgcm/test/*
       xgcm/__init__.py
```

**Comment by rabernat** [comment]
No luck:
https://travis-ci.org/xgcm/xgcm/jobs/105919835

**Pull request merged**
